### ISSUE TITLE
Feature01 - Allow user to Add Tasks

### ISSUE THREAD

**Issue by NishadChayanakhawa** [NishadChayanakhawa/task-vault#2]
**Task Attributes**

- ID
- Group Name
- Summary
- Description
- Mail Subjects [Subject1,Subject2,...]
- Status - To Do, In Progress, Completed, Cancelled
- Due On
- Next Follow-up On
- Session - Session I, Session II or Session III
- SubTasks - [{SubTaskDescription,completionFlag}]
- Notes - [{Entry,Date}]
- TimeLogs - [{startTime,endTime},{startTime,endTime}]
- Time Spent

**Tasks**

- [ ] Develop Beans
- [ ] Develop Processing Module
- [ ] Test Processing Module and Beans
- [ ] Develop API
- [ ] Test APIs
- [ ] Create Sample Front end
- [ ] Develop front end
- [ ] Write JQuery
- [ ] Test Front end
